=== ealight/bailbotsframework/src/main/resources/xsd/inlineKeyboard.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inline-keyboard">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="inline-db-keyrow" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:string" name="entity" use="required"/>
                                <xs:attribute type="xs:string" name="maxItemsOnPage" use="required"/>
                                <xs:attribute type="xs:string" name="methodForName" use="required"/>
                                <xs:attribute type="xs:string" name="methodForCallback" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="inline-keyrow" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inline-button" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="callback" use="required" default="none"/>
                                            <xs:attribute type="xs:boolean" name="pageable"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="controller"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ealight/bailbotsframework/src/main/resources/keyboard/inline/houseItem.xml
<?xml version="1.0"?>

<inline-keyboard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../../xsd/inlineKeyboard.xsd"
                 controller="House">

    <inline-keyrow>
        <inline-button callback="MorePhoto">Больше фото</inline-button>
        <inline-button callback="Detail">Детальнее</inline-button>
        <inline-button callback="OwnerRequirements">Требования владельца</inline-button>
        <inline-button callback="AdditionalService">Дополнительные услуги</inline-button>
    </inline-keyrow>

    <inline-keyrow>
        <inline-button callback="Book">Забронировать</inline-button>
    </inline-keyrow>

</inline-keyboard>
